In [1]:
import numpy as np

array_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:", array_1d)
print("Shape:", array_1d.shape)
print("Size:", array_1d.size)
print("Data type:", array_1d.dtype)

array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("\n2D Array:", array_2d)
print("Shape:", array_2d.shape)
print("Size:", array_2d.size)
print("Data type:", array_2d.dtype)

array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("\n3D Array:", array_3d)
print("Shape:", array_3d.shape)
print("Size:", array_3d.size)
print("Data type:", array_3d.dtype)

python_list = [10, 20, 30]
numpy_array = np.array(python_list)
print("\nConverted NumPy Array:", numpy_array)

zeros_array = np.zeros((5, 5))
print("\n5x5 Array of Zeros:\n", zeros_array)

ones_array = np.ones((4, 4))
print("\n4x4 Array of Ones:\n", ones_array)

specific_value_array = np.full((3, 3), 7)
print("\n3x3 Array filled with 7:\n", specific_value_array)

identity_matrix = np.eye(6)
print("\n6x6 Identity Matrix:\n", identity_matrix)

even_spaced_1 = np.linspace(0, 20, 5)
even_spaced_2 = np.arange(0, 21, 5)
print("\nEvenly spaced numbers using linspace:", even_spaced_1)
print("Evenly spaced numbers using arange:", even_spaced_2)

arr_int = np.array([1, 2, 3])
print("\nOriginal data type of arr_int:", arr_int.dtype)

arr_float = arr_int.astype(float)
print("Array converted to float:", arr_float)
print("Data type after conversion:", arr_float.dtype)

arr_int_converted = arr_float.astype(int)
print("Array converted back to integer:", arr_int_converted)
print("Data type after conversion:", arr_int_converted.dtype)

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

addition = arr1 + arr2
subtraction = arr1 - arr2
multiplication = arr1 * arr2
division = arr1 / arr2
print("\nAddition:", addition)
print("Subtraction:", subtraction)
print("Multiplication:", multiplication)
print("Division:", division)

exponentiation = np.power(arr1, 2)
square_root = np.sqrt(arr1)
logarithm = np.log(arr1)
print("\nExponentiation:", exponentiation)
print("Square root:", square_root)
print("Logarithm:", logarithm)

print("\nMean:", np.mean(arr1))
print("Sum:", np.sum(arr1))
print("Standard Deviation:", np.std(arr1))
print("Variance:", np.var(arr1))
print("Max value:", np.max(arr1))
print("Min value:", np.min(arr1))

result = arr1 * arr2
print("\nElement-wise multiplication:", result)

scalar_mult = arr1 * 10
print("Array multiplied by scalar:", scalar_mult)

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

filtered = arr[arr > 5]
print("\nValues greater than 5:", filtered)

even_numbers = arr[arr % 2 == 0]
print("Even numbers:", even_numbers)

odd_numbers = arr[arr % 2 != 0]
print("Odd numbers:", odd_numbers)

replaced_values = np.where(arr > 5, 100, arr)
print("Array with values > 5 replaced by 100:", replaced_values)

array_4x4 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])

specific_element = array_4x4[1, 2]
print("\nSpecific element (row 2, col 3):", specific_element)

selected_row = array_4x4[2, :]
selected_column = array_4x4[:, 1]
print("Selected row (row 3):", selected_row)
print("Selected column (col 2):", selected_column)

negative_index = array_4x4[-1, -1]
print("Element using negative indexing:", negative_index)

sub_matrix = array_4x4[1:3, 1:3]
print("\n2x2 Sub-matrix:\n", sub_matrix)

reversed_array = array_4x4[::-1, ::-1]
print("Reversed array:\n", reversed_array)

array_3x4 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

transposed_array = array_3x4.T
print("\nTransposed Array:\n", transposed_array)

print("Shape before transposing:", array_3x4.shape)
print("Shape after transposing:", transposed_array.shape)

swapped_2d = array_3x4.swapaxes(0, 1)
print("\n2D Array with swapped axes:\n", swapped_2d)

array_3d_swapped = array_3d.swapaxes(0, 2)
print("3D Array with swapped axes:\n", array_3d_swapped)

import pandas as pd

series_list = pd.Series([1, 2, 3, 4, 5])
print("\nPandas Series from list:\n", series_list)

series_array = pd.Series(np.array([10, 20, 30, 40]))
print("\nPandas Series from NumPy array:\n", series_array)

series_dict = pd.Series({"a": 1, "b": 2, "c": 3})
print("\nPandas Series from dictionary:\n", series_dict)

series_custom_index = pd.Series([1, 2, 3], index=["x", "y", "z"])
print("\nSeries with custom index:\n", series_custom_index)

data_dict = {"Name": ["Alice", "Bob"], "Age": [24, 27]}
df_dict = pd.DataFrame(data_dict)
print("\nDataFrame from dictionary:\n", df_dict)

data_array = np.array([["Alice", 24], ["Bob", 27]])
df_array = pd.DataFrame(data_array, columns=["Name", "Age"])
print("\nDataFrame from NumPy array:\n", df_array)

df_array["Country"] = ["USA", "Canada"]
print("\nDataFrame with new column:\n", df_array)

df1 = pd.DataFrame({"Name": ["Alice", "Bob"], "Age": [24, 27]})
df2 = pd.DataFrame({"Name": ["Charlie", "David"], "Age": [30, 35]})

concat_row = pd.concat([df1, df2], axis=0)
print("\nRow-wise concatenation:\n", concat_row)

concat_col = pd.concat([df1, df2], axis=1)
print("\nColumn-wise concatenation:\n", concat_col)

df3 = pd.DataFrame({"Name": ["Alice", "Bob"], "City": ["NYC", "LA"]})
merged = pd.merge(df1, df3, on="Name")
print("\nMerging on Name:\n", merged)

joined = df1.join(df3.set_index("Name"), on="Name")
print("\nJoined DataFrame:\n", joined)

sorted_df = df1.sort_values(by="Age")
print("\nSorted by Age:\n", sorted_df)

sorted_multi_df = df1.sort_values(by=["Name", "Age"])
print("\nSorted by Name and Age:\n", sorted_multi_df)

sorted_index_df = df1.sort_index()
print("\nSorted by index labels:\n", sorted_index_df)

arrays = [np.array([1, 1, 2, 2]), np.array(["A", "B", "A", "B"])]
index = pd.MultiIndex.from_arrays(arrays, names=("level1", "level2"))
df_multi = pd.DataFrame({"Value": [10, 20, 30, 40]}, index=index)
print("\nMulti-index DataFrame:\n", df_multi)

selection = df_multi.loc[1]
print("\nSelection for level1 = 1:\n", selection)

data = np.random.randn(100)
print("\nMean:", np.mean(data))
print("Median:", np.median(data))

df = pd.DataFrame({"Data": data})
print("\nSummary statistics:\n", df.describe())


1D Array: [1 2 3 4 5]
Shape: (5,)
Size: 5
Data type: int64

2D Array: [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Size: 6
Data type: int64

3D Array: [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Shape: (2, 2, 2)
Size: 8
Data type: int64

Converted NumPy Array: [10 20 30]

5x5 Array of Zeros:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

4x4 Array of Ones:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

3x3 Array filled with 7:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

6x6 Identity Matrix:
 [[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]

Evenly spaced numbers using linspace: [ 0.  5. 10. 15. 20.]
Evenly spaced numbers using arange: [ 0  5 10 15 20]

Original data type of arr_int: int64
Array converted to float: [1. 2. 3.]
Data type after conversion: float64
Array converted back to integer: [1 2 3]
Data type after conversion: int64

Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multi